src/monitor/tedge-container-monitor

Fix bug caused by invalid docker cli syntax

fix: container stats collection bug

---

README.md

* Include notes about the required suffix required in the version string in Cumulocity IoT
* Fix typos in README.md

fix: update readme to include notes about required version suffix

---

.github/workflows/test.yaml
.gitignore
docker-compose.yaml
images/Dockerfile
images/container-env
justfile
tests/data/docker-compose.nginx.yaml
tests/data/tedge-configuration-plugin.toml
tests/operations.robot
tests/requirements.txt
tests/resources/common.robot
tests/telemetry-main.robot

Add some system tests and workflow which will be run on PR checks

add system tests and workflow

---

.github/workflows/test.yaml

Add missing link from the test job to the approve job.

ci: fix job dependency to approve

---

ui/README.md

docs(ui): update condition in which ui tabs are activated

---

.github/workflows/test.yaml

Refactor checkout logic to reduce amounts of conditionals

ci: simplify test workflow checkout logic

---

ui/package.json

Preparing for a release (new ui version)

bump ui version

---

pkg/app/app.go

Avoid updating and publishing events on container exec commands which can be run to check the health of a container, so these should not be published back to the platform.

fix: only publish on exec_die if it is related to the main process

---

src/monitor/scripts/post-install
src/monitor/scripts/post-remove
src/monitor/scripts/pre-remove

The service is now stopped and removed when the package is removed.

fix(packaging): Stop and remove service when package is removed

---

cli/container/install.go
cli/container/remove.go

Add some examples to the cli commands (to help with local testing)

feat(container): add examples for installing and removing a container

---

pkg/app/app.go

Fixing a bug in the original PR (https://github.com/thin-edge/tedge-container-plugin/pull/65) which was caused by a logic inversion, though further debugging revealed that the exec events were still spamming the logs.
Refactored to simplify the logic by using an early return and to ignore all exec events with an `execID` field.

fix(monitor): ignore all exec event types not directly related to the main process

---

pkg/container/container.go

Improve podman api endpoint detection by:
* Checking `unix:///run/user/0/podman/podman.sock`
* Checking `CONTAINER_HOST` env variable
After the socket is detected, improve compatibility to other tooling by setting:
* env variable `DOCKER_HOST`
* env variable `CONTAINER_HOST`

feat: improve detection of podman sockets

---

.github/workflows/test.yaml
README.md
justfile
tests/operations-private-registries.robot
tests/resources/common.robot

Reduce the number of variables that have to be set to select the image used in testing. Additional variables were also removed from the ci workflow.

tests: simplify test image selection

---

cli/tools/cmd.go
cli/tools/container_logs.go
pkg/container/container.go
tests/container-logs.robot

Add in-built command to fetch container logs (for internal use only).

feat: add internal command to get container logs

---

.github/workflows/test.yaml
cli/container/list.go
cli/self/list.go
justfile
pkg/container/container.go
pkg/container/container_test.go
tests/data/apps/app1/Dockerfile
tests/data/apps/app2/Dockerfile
tests/data/apps/app3/Dockerfile
tests/operations-clone.robot
tests/operations-private-registries.robot
tests/operations.robot

Use the full image name in the version field to ensure version comparisons work correctly in the UI.

fix(container): use full image in version field

---

cli/container/install.go

Set the network mode as it is required on some older versions of container engines (e.g. podman v4.x).

fix(container): set network mode when creating a container

---

.goreleaser.yaml
cli/self/check.go
tests/self.robot

Improve detection of self updates by checking the `container` module type in addition to `self`.

feat(container): provide tool to check for self updates and filter from module list

---

cli/container/finalize.go
cli/self/finalize.go
packaging/config.toml
pkg/container/container.go
pkg/container/container_test.go
pkg/container/socket_client.go

Prune images by default when using sm-plugins , container and container-group.

feat: prune images by default

---

ui/package-lock.json
ui/package.json
ui/src/container-management/container-filter.pipe.ts
ui/src/shared/container-service.ts

ci: fix ui build workflow

---

README.md

Fix invalid markdown url link to goreleaser.

docs: fix markdown url link to goreleaser

---

.gitignore
tests/data/apps/app5/docker-compose.yaml
tests/data/apps/app5/htdocs/index.html
tests/data/apps/build.sh
tests/operations.robot

Add a test to verify that users can create a docker-compose.yaml file which uses a host mounted volume with files included in the tarball

tests: add test for verifying host volume mounts
