thin-edge/tedge-container-plugin

src/monitor/tedge-container-monitor
Read the service name from the docker ps command instead of from the input arguments.
=> fix: container meta information publishing to non-existent service name

src/monitor/tedge-container-monitor
Add support for the collection of meta data and telemetry for container groups (e.g. docker compose projects)
Resolves #7
=> feat: collect container-group data

docs/TELEMETRY.md, src/monitor/tedge-container-monitor
.status is already provided by the service health api.
Avoid overwriting the already existing .status property which is provided by the health endpoint (e.g. up/down)
=> fix: rename .status to .containerStatus

src/monitor/tedge-container-monitor
Fix an issue where publishing to `tedge/measurements/{service_name}` generates child devices (instead of child services).
Until a dedicated topic is added to thin-edge.io, the measurements are published directly to the `c8y/measurement/measurements/create` topic.
=> fix: use c8y/measurements topic to prevent child device creation

src/monitor/tedge-container-monitor
Fix a refactoring mistake where the container-group inventory updates were being published to the incorrect external id.
=> fix: prefix the container-group meta information with the parent device id

src/monitor/tedge-container-monitor
The bug occurred if no matching containers or container groups were found, then the cli would match all containers. Added a check for empty results to avoid this.
=> fix(monitor): Don't collect metrics if no matching containers or container groups are found

docs/TELEMETRY.md, src/container, src/container-group, src/monitor/tedge-container-monitor, ui/package.json, ui/src/shared/container-service.ts
Switch to use the new thin-edge.io MQTT api (e.g. `te/` topics instead of the `tedge/` topics, see [docs](https://thin-edge.github.io/thin-edge.io/next/references/mqtt-api/) for details).
Warning this is a breaking change and will requires thin-edge.io >= 0.13.0 (or the latest in the main branch, e.g. >=0.12.1~528+ge11b64f)
* Publish container measurements using the type `resource_usage` (previously it was the default type `ThinEdgeMeasurement`
* Container metrics (c8y inventory data) is published to new `/twin/container` topic, which is then published to the Cumulocity device managed object under the `container` fragment
* Publish service health status to new tedge topic `te/device/main/service/<container_id>/...` 
* Changed container names to use the `@` separator instead of `::` (e.g. …
=> use tedge mqtt v1 api to publish telemetry data

src/monitor/tedge-container-monitor
fix the service type used when registering the services. Manual registration messages are now sent which included the expected service types (`container` and `container-group`).
=> fix: register services with correct service type

src/monitor/tedge-container-monitor
service type information should only be part of the registration messages and not the status/health messages
Publishing the type information in the stat/health message does not break anything however it is not best practice.
=> fix: remove type information from health messages

docs/TELEMETRY.md, src/container-group, tests/operations.robot
Fix a problem with the container-group service status where the service name used to publish the `uninstalled` status was using `::` instead of `@` as the compose project/service separator.
The up status was already using the `@` separator.
**Before**
name: `myproject::nginx`
**After**
name: `myproject@nginx`
=> fix(container-group): fix the service type when publishing the down status

README.md
Update the README to align with thin-edge.io v1, for example use the softwareType rather than using the `::<type>` syntax.
=> docs: update readme to align with thin-edge.io v1

.gitignore, .vscode/settings.json, README.md
Add instructions on how to run system tests locally, and include sensible defaults for VS Code.
=> dev: update developer instructions

src/container-group
Fix a minor bug where checking the container-group file type (using `file`) would generated large stderr output, now the stderr is ignored when detecting the file type.
=> fix(container-group): ignore stderr when checking file type as stderr can be spammed

ui/package-lock.json, ui/package.json, ui/src/shared/container.guard.ts
Previously the "container" and "container-group" tabs were only appearing if there was at least 1 "container" service deployed, and it would not display if there were only container-groups deployed.
Now having at least 1 container or 1 container-group will activate both of the tabs.
=> fix(ui): display container and container-groups tabs when either type is present

.github/workflows/release.yaml
Minor workflow improvements
* update actions which were using the deprecated nodejs 16.x
* disable golang cache detection to reduce noise
* add UI version to the UI zip package to make it easier to identify and already downloaded artifact
=> ci: update ci workflows dependencies and add version to ui package

.github/workflows/test.yaml
Fix minor warnings in the test workflow:
* install just via `taiki-e/install-action@just` as it does not use the now deprecated nodejs 16.x
* Disable cache when installing golang
=> ci: fix warnings in test workflow

src/monitor/tedge-container-monitor
Remove the pid from the service status messages as it was causing the service status message to be ignored by thin-edge.io (due to the pid data type changing from a string to an integer).
Since the pid information did not provide any useful information, it was removed all together.
=> fix: remove pid from service status messages

src/monitor/tedge-container-monitor, tests/telemetry-main.robot
Resolves https://github.com/thin-edge/tedge-container-plugin/issues/37
The container monitor service would remain in the "down" status if the connection to mosquitto would be interrupted for any reason (e.g. if mosquitto is restarted).
Now, the LWT is not used to publish the service "down" message as mosquitto_sub does not offer a way to published a message on reconnection.
=> test: check monitor status after restarting mosquitto

.github/workflows/release.yaml
Avoid problems when using the default globally installed nodejs version on the runner image. Use the setup-node to control the nodejs version instead.
=> ci: use setup-node to install specific nodejs version

nfpm.yaml
Systemd service definitions should not be marked as executable as unit files are only configuration.
Otherwise systemd shows a warning when installing the service:
```
Synchronizing state of tedge-container-monitor.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable tedge-container-monitor
Configuration file /lib/systemd/system/tedge-container-monitor.service is marked executable. Please remove executable permission bits. Proceeding anyway.
```
=> fix(packaging): remove executable permission bits from systemd service definition

ui/src/shared/container.guard.ts
Prevent a false positive against the kedge-agent (for thick edge), where it registers the services with the serviceType `container` (the same as used by tedge-container-plugin).
Resolves #51.
=> fix: include check for container fragment to reduce false positives

src/container-group
Similar to https://github.com/thin-edge/tedge-container-plugin/pull/56, the container-group sm-plugin will also try to create the `tedge` network container so that the container-groups can use a common network because external networks aren't created by docker compose.
The network name can be controlled via `CONTAINER_DEFAULT_NETWORK`
=> feat(container-group): create common container network

src/container, src/container-group
Don't use absolte paths to allow users to also override the `tedge-container-monitor` command if necessary
=> feat: avoid using absolute paths when calling tedge-container-monitor

nfpm.yaml, src/container-cli
The new command `container-cli` allows users to call the container commands (and add it to the sudoers rule) without having to know the underlying container cli
=> feat: add new container-cli command

src/container, src/container-group
Support for upcoming tedge-container-monitor rewrite. Add an option to disable the current (soon to be legacy) mechanism to update the service status
=> feat: add option to disable legacy (current) container status update

src/container-group
Only call the new container status update after finishing the compose down calls
=> fix(container-group): trigger new status update after full removal

README.md, packaging/config.toml
Add comments to the default configuration file, and update the README.d to direct the user to the default `config.toml` file.
=> docs: add comments to configuration properties

pkg/container/compose.go, test-images/debian-systemd-docker-cli/Dockerfile, test-images/debian-systemd-podman-cli/Dockerfile, tests/data/apps/app1/Dockerfile, tests/data/apps/app2/Dockerfile, tests/data/apps/app3/Dockerfile, tests/data/docker-compose.nginx.yaml, tests/installation.robot, tests/operations.robot
podman-compose does not support `podman-compose down --remove-orphans`, so the command is normalized and the argument is removed when preparing the compose cli command.
The system tests were also updated to use fully qualified image names so that podman can resolve the container images.
=> fix(podman): strip incompatible cli arguments from podman-compose down command

go.mod
Allow building with golang 1.22 which is the current supported version in the Yocto kirkstone lts-mixin.
=> feat: support golang 1.22 (for Yocto kirkstone lts-mixin)

cli/container/install.go
Fix the image name detection used when loading the container image from file.
The main bug was that trailing `\n` characters were not being stripped from the name.
Now a more robust parsing method is supported where it can also detect if multiple images are detected within the image. The first found image will be used as the image ref.
=> fix(container): container file image name detection

cli/container_group/install.go, packaging/config.toml, pkg/cli/cli.go, pkg/utils/utils.go
Support changing the data directory used when installing container-groups. On read-only root filesystems, this value needs to be configurable otherwise the container-group feature does not work.
=> feat(config): add data_dir config setting

pkg/container/docker.go
Support detecting `podman-remote` cli when running `tedge-container engine docker`
=> feat: include podman-remote cli detection

cli/container_group/install.go, packaging/config.toml, pkg/cli/cli.go, pkg/utils/utils.go, pkg/utils/utils_test.go, tests/operations.robot
Fix an issue with the persistent directory selection where the plugin's configuration file was not being used when running the sm-plugins.
In addition, the persistent directory now follows the logic:
* Select first writable directory where the root diretory exists
* Set default configuration file to the TEDGE_CONFIG_DIR plugins folder
=> fix: persistent directory handling in sm-plugins

cmd/root.go, pkg/container/compose_test.go, pkg/container/container.go, tests/data/docker-compose.invalid.yaml, tests/operations.robot
Due to a limitation with podman-compose, parse the exit code from stderr and propogate it back.
Resolves https://github.com/thin-edge/tedge-container-plugin/issues/70
=> fix: parse podman-compose output to check for non-zero exit code

.goreleaser.yaml, packaging/services/s6-overlay/tedge-container-plugin-log/consumer-for, packaging/services/s6-overlay/tedge-container-plugin-log/pipeline-name, packaging/services/s6-overlay/tedge-container-plugin-log/run, packaging/services/s6-overlay/tedge-container-plugin-log/type, packaging/services/s6-overlay/tedge-container-plugin/producer-for, packaging/services/s6-overlay/tedge-container-plugin/run, packaging/services/s6-overlay/tedge-container-plugin/type
Support for running the tedge-container-plugin service under s6-overlay service manager (for alpine packages only).
Note, the s6-overlay definitions were taken from the template files in the [tedge-services](https://github.com/thin-edge/tedge-services/tree/main/services/s6-overlay/templates) project.
=> feat(packaging): add s6-overlay service definitions to alpine package

pkg/container/docker.go
Fixing minor error when no container cli (e.g. docker, podman or podman-remote) is found. Previously the error would return "compose cli not found" giving the wrong impression that it was looking for compose and not the container engine cli
=> fix: error message when no container cli tool is found

packaging/services/s6-overlay/tedge-container-plugin/run
Fix a bug where the tedge-container-plugin s5-overlay service was not being launched with root access to the container engine socket resulting in permission denied errors for the monitoring functionality.
=> fix: launch s6-overlay service with sudo rights

packaging/services/s6-overlay/tedge-container-plugin/finish
Since the tedge-container service needs access to the container engine socket, it is launched with using sudo, however this means that the s6-overlay shutdown signals are ignored (as the shutdown signal is sent by a non-root user).
Instead, a manual s6-overlay "finish" script is used to kill the service using sudo.
=> fix(s6-overlay): shutdown of service when run as root

.github/workflows/test.yaml, .gitignore, README.md, cli/container/install.go, docs/CONTAINER_REGISTRIES.md, justfile, packaging/config.toml, pkg/cli/cli.go, tests/data/apps/app4/Dockerfile, tests/data/apps/app4/docker-compose.yaml, tests/data/apps/build.sh, tests/data/registry-credentials, tests/installation.robot, tests/operations-private-registries.robot, tests/operations.robot, tests/telemetry-main.robot
In addition to the standard way of support private repository credentials using the standard `docker login` or `podman/podman-remote login`, tedge-container-plugin supports setting the container repository credentials which are used by the `container` sm-plugin when pulling in new images.
See the [docs](https://github.com/thin-edge/tedge-container-plugin/blob/7649e6873e7302a48de214cf3f0c082a3489fc13/docs/CONTAINER_REGISTRIES.md) for details.
Though currently pulling from private repositories is not supported when using `container-group` as currently the image pull is performed by `docker compose` (or `podman-compose`), and not the tedge-container-plugin.
=> feat: support private registries

cli/container/install.go, docs/CONTAINER_REGISTRIES.md, go.mod, pkg/cli/cli.go, pkg/container/container.go, pkg/utils/utils.go, tests/data/registry-credentials-with-cache, tests/operations-private-registries.robot
Improve pulling images from public and private repositories by:
* Support calling the registry-credentials script again if the first image pull attempt fails (with an additional flag `--refresh`) to indicate that the previously provided value may not be valid any more.
* Fix container image reference parsing to check the domain name.
=> feat: improve image pull and private repo handling

.goreleaser.yaml, cli/container/install.go, cli/engine/cmd.go, cli/engine/container_clone.go, cli/engine/docker.go, cli/self/check.go, cli/self/cmd.go, cli/self/finalize.go, cli/self/install.go, cli/self/list.go, cli/self/prepare.go, cli/self/remove.go, cli/self/updateList.go, cli/tools/cmd.go, cli/tools/container_clone.go, cmd/root.go, justfile, pkg/cli/cli.go, pkg/container/auth.go, pkg/container/container.go, pkg/container/stdcopy.go, pkg/utils/utils.go, tests/operations-clone.robot
Add `tools` subcommand to provide some core functionality when dealing with containers. This is only meant for internal use only, as the commands can change at any time!
* `clone-container` - clone an existing container and replace the image name
=> feat: add commands to clone a container

cli/tools/container_clone.go, pkg/container/container.go
Compatibility improvements to support cloning containers (used in self-updates) for podman v4.x
=> fix: container clone compatibility with podman v4

cli/tools/container_clone.go, pkg/container/container.go
Allow the user to control when the container is stopped
=> feat(internal): add stop-after to container-clone

cli/container_group/finalize.go
Prune container images when running the finalize command for the `container-group` sm-plugin if the feature is enabled, e.g. `container.pruneImages`.
=> feat(container-group): prune images during container-group finalize hook

.goreleaser.yaml
Install the `tedge-container-plugin.toml` configuration file under the `/etc/tedge/plugins` folder so it can be easily accessed and backed up with other tedge config.
=> fix: install configuration file under tedge plugins folder

cli/self/cmd.go, cli/self/list.go
Provide the `self` sm-plugin to enable updating from legacy versions but don't print out the list of software items (to avoid duplciate entries as the `container` type.
=> fix: only use self sm-plugin for legacy updates

pkg/container/container.go
In docker, images which are pulled with `docker.io/library/<name>` don't match against the full image name when using ImageList API. Image inspect does not suffer from this problem.
=> fix: docker image detection compatibility for default repos

cli/tools/container_clone.go, cli/tools/run_context.go, pkg/container/container.go, tests/operations-clone.robot
Add flag to allow commands to specify additional labels that should be added to container when launching them. This will help other commands to control where the forked containers should be monitored by the tedge-container-plugin service or not.
=> feat(internal): allow users to add labels when cloning container or running in context

cli/tools/cmd.go, cli/tools/container_clone.go, cli/tools/container_remove.go, cli/tools/run_context.go, pkg/container/container.go, pkg/random/random.go
Add options to internal tools to improve the tedge-container-bundle feature set:
* Control container names whilst using `container-clone`
* Allow user to control the container prefix using `run-in-context`
* Add command to stop and remove a container
=> feat(internal): improvements to internal cli tools

packaging/services/init.d/service.init, packaging/services/s6-overlay/tedge-container-plugin/run, packaging/services/systemd/tedge-container-plugin.service, pkg/cli/cli.go
Fix configuration path referenced by services to use the updated config file location to `/etc/tedge/plugins/tedge-container-plugin.toml`
=> fix(config): update config path reference used by service definitions

cli/container_group/install.go, cli/container_group/remove.go, pkg/container/container.go
Improve logging on the `container-group` sm-plugin when removing existing compose groups to help diagnose unexpected errors.
=> feat(container-group): improve logging when removing a compose project

cli/tools/container_remove.go, tests/container-remove.robot
Fix a bug where the `tedge-container tools container-remove` command was calling the incorrect command.
=> fix(internal): fix container-remove command and add test

cli/container/finalize.go, cli/container_group/finalize.go, pkg/container/container.go, tests/container-logs.robot, tests/container-remove.robot
Whilst pruning images using the equivalent to `docker image prune -a` to remove all unused images (not just the dangling ones).
=> fix: prune unused images not just dangling

.goreleaser.yaml
Replace usage of deprecated `archive.format` property and use `archive.formats` instead (which is an array).
=> chore: remove usage of deprecated gorelease archive.format property

.gitignore, package-lock.json, ui/.browserslistrc, ui/angular.json, ui/app.module.ts, ui/bootstrap.ts, ui/cumulocity.config.ts, ui/jest.config.js, ui/main.ts, ui/package-lock.json, ui/package.json, ui/polyfills.ts, ui/src/branding/branding.less, ui/src/container-info/container-info.module.ts, ui/src/container-management/container-management.module.ts, ui/src/group-management/group-management.module.ts, ui/src/shared/container.guard.ts, ui/tsconfig.json, ui/tsconfig.spec.json
This PR contains the upgrade of the UI for the container plugin from webSDK 1018/angular 15 -> webSDK 1020/angular 17
=> feat: migrate ui to c8y version 1020

pkg/container/container.go, pkg/container/container_test.go
Exclude all oci labels whilst cloning a container (e.g. `org.opencontainers.*`) to avoid overwriting the labels which are included in the new image.
=> fix: exclude oci labels when cloning a container

cli/tools/cmd.go, cli/tools/container_restart.go, pkg/container/container.go, tests/container-restart.robot
New command (for internal use only) to support restarting containers. If no container id is provided it will check if the command is being from run inside a container and use that to restart itself (consistent with such other `container-*` helper commands.
=> feat(container-tools): add a container-restart command

cli/tools/container_clone.go, cli/tools/run_context.go, pkg/container/container.go
Fix minor typos in the help and log output
=> fix: fix typos in help text and log output

pkg/container/container.go, pkg/container/socket_client.go
Due to a podman issue (experienced in podman 4.4), sometimes doing a `docker pull` fails for the following reason:
```
write /dev/stderr: input/output error
```
The PR adds logic to attempt to do a manual `podman pull` (via API) which does not seem to suffer the same problem.
This bug is most likely fixed in newer versions of podman (e.g. 5.x), though it is difficult for some users to update the podman versions.
=> feat: try pulling images using podman api directly

README.md
Fix some broken links refering to the Cumulocity UI extension.
=> docs: fix ui links to tedge-container-plugin-ui repository

packaging/services/init.d/service.init
Fix the command used to start the sysvinit service where the binary command was just duplicated (copy/paste error).
The bug was spotted by @zhongys-c8y in https://github.com/thin-edge/tedge-container-plugin/issues/134 (though the ticket is otherwise unrelated).
=> fix(sysvinit): fix service start command

.goreleaser.yaml, packaging/scripts/post-install, packaging/scripts/post-remove, packaging/services/openrc/tedge-container-plugin.conf, packaging/services/openrc/tedge-container-plugin.init, test-images/alpine-openrc-podman-cli/Dockerfile, tests/operations.robot
Add OpenRC service definitions to the Alpine Linux package (.apk). The files will only be used if OpenRC is detected during installation time.
The feature is still marked as experimental as the system tests setup needs to be updated to support an Alpine Linux based image and there seems to be some problems getting podman to be functional within the system test container.
This is purely a packaging change and no other functional changes are included
=> feat(experimental): add openrc service definitions to apk package

tests/installation.robot, tests/operations-clone.robot, tests/operations-private-registries.robot, tests/operations.robot, tests/resources/common.robot, tests/self.robot
Define a log collection keyword in the common resource so it can be reused in all tests.
The log collection now ignores common kernel audit messages in an effort to reduce the noise within the collected logs.
=> tests: use common log collection keyword

.goreleaser.yaml
Update the goreleaser config to remove the deprecated config property names `builds` => `ids`
=> chore: rename deprecated goreleaser config

.goreleaser.yaml, cli/run/cmd.go, packaging/config.toml, pkg/app/app.go, pkg/cli/cli.go, pkg/tedge/target.go, pkg/tedge/tedge.go
Refactor to use the new thin-edge.io [REST API for Entity Management](https://thin-edge.github.io/thin-edge.io/operate/registration/register/) which allows the service entities to be registered and deregistered more easily by sending a single HTTP request and all of the related topics are cleanly removed (rather than having to subscribe to the different topics manually).
Since this change relies on having tedge >= 1.5.0 installed, an explicit dependency has been added to the deb and rpm packages (but not the Alpine Linux packages due to how the tedge container image does not have the tedge apk package installed, just the binaries).
=> refactor: use tedge entity store api for registration

pkg/app/app.go, pkg/tedge/tedge.go
Fix some errors in loading the entity store api
* use the entity store HTTP api to get a list of the entities instead of using MQTT
* fix an inversion logic when checking the response from the entity store HTTP api
* Add workaround to manually clear the MQTT health status message as the entity store HTTP api does not seem to remove when deregistering a device
Related issues:
* https://github.com/thin-edge/tedge-container-plugin/issues/145
=> fix: entity store api

cli/run/cmd.go, packaging/config.toml, pkg/app/app.go, pkg/cli/cli.go, tests/operations.robot
Support removing any orphaned services from the cloud which were previously created with the `container` or `container-group` service type and no longer have any thin-edge.io related entity registered.
This function is only enabled if both settings are true:
* `delete_from_cloud.enabled`
* `delete_from_cloud.orphans`
=> feat: delete orphaned services from previously created containers

.goreleaser.yaml, README.md
The `tedge-container-plugin.toml` file wasn't marked as a "config" in the linux packaging definition when meant it would be overridden when upgrading the package.
=> fix(packaging): set the config type when building the linux package

.goreleaser.yaml, packaging/services/openrc/tedge-container-plugin.conf
Fix the Alpine Linux packaging of the OpenRC service configuration where it would previously overwrite the `tedge-container-plugin.conf` which could of been edited by the user.
=> fix: preserve OpenRC conf file on package updates

pkg/container/container.go
Remove an erroneous warning message which was printed when stopping a container-group. It would result in a warning message "compose failed." always being printed even if there was no error.
=> fix: remove erroneous compose command failed log message
